#' Identify Water-Bound Sampling Locations and Perform Snap-to-Land Alignment
#'
#' @description
#' Evaluates geographic sampling sites against a CRU climate raster to detect points
#' falling into water body cells (where raster value is \code{NA}). For every identified
#' water point, the function performs a localized spatial search to identify the nearest
#' valid land cell (Snap-to-Land).
#'
#' @param output_spaziale A \code{list} generated by \code{estrai_metadati_e_master()} containing:
#'   \describe{
#'     \item{\code{df_coor}}{A \code{data.frame} containing metadata and definitive coordinates (\code{lon_definitiva}, \code{lat_definitiva}).}
#'     \item{\code{punti_vect}}{A \code{terra::SpatVector} representing the geographic locations.}
#'   }
#' @param path_raster_cru A \code{character} string specifying the file path to the reference CRU NetCDF file (e.g., \code{"CRU_TS_pre.nc"}).
#'
#' @return A \code{data.frame} containing only the sampling sites that fall into water cells,
#' or \code{NULL} if no water-bound sites are detected. The returned data frame inherits all
#' original columns from \code{df_coor} plus two additional snap-alignment columns:
#'   \describe{
#'     \item{\code{...}}{All original columns from \code{df_coor} (e.g., \code{stand_id}, \code{lon_definitiva}, \code{lat_definitiva}, etc.).}
#'     \item{\code{lon_snap}}{\code{numeric}. Nearest land cell longitude calculated via snap-to-land.}
#'     \item{\code{lat_snap}}{\code{numeric}. Nearest land cell latitude calculated via snap-to-land.}
#'   }
#'
#' @importFrom terra rast extract crds ext crop as.points nearest
#' @export
#'
#' @examples
#' \dontrun{
#' # Execute water check on spatial output list
#' report_water <- gestisci_punti_in_acqua(
#'   output_spaziale = output_spaziale,
#'   path_raster_cru = "data/CRU_TS_pre.nc"
#' )
#'
#' # Inspect identified water stands and calculated snap coordinates
#' if (!is.null(report_water)) {
#'   head(report_water[, c("stand_id", "lon_definitiva", "lat_definitiva", "lon_snap", "lat_snap")])
#' }
#' }

gestisci_punti_in_acqua<- function(output_spaziale, path_raster_cru) {

  df_coor    <- output_spaziale$df_coor
  punti_vect <- output_spaziale$punti_vect

  # Se l'oggetto è stato salvato con wrap(), lo spacchettiamo con unwrap()
  if (inherits(punti_vect, "PackedSpatVector")) {
    punti_vect <- terra::unwrap(punti_vect)
  }

  # 1. Carica raster CRU
  raster_cru <- terra::rast(path_raster_cru)[[1]]

  # 2. Estrai valore CRU per ciascun punto
  valori_cru <- as.numeric(terra::extract(raster_cru, punti_vect, ID = FALSE)[[1]])

  # 3. Trova quali punti sono in acqua (NA su CRU)
  idx_acqua <- which(is.na(valori_cru))

  if (length(idx_acqua) == 0) {
    message("Great! No stands were found in water body cells.")
    return(NULL)
  }

  # 4. Isoliamo solo le righe degli stand in acqua
  df_res <- df_coor[idx_acqua, , drop = FALSE]
  punti_acqua <- punti_vect[idx_acqua]

  # 5. Snap-to-land: trova la cella di terra più vicina per ciascun punto
  lons_snap <- numeric(length(idx_acqua))
  lats_snap <- numeric(length(idx_acqua))

  for (j in seq_along(idx_acqua)) {
    p_singolo <- punti_acqua[j]
    coords_p  <- terra::crds(p_singolo) # lon, lat originali

    # Finestra di ricerca attorno al punto (~250 km)
    ext_loc <- terra::ext(coords_p[1] - 2.5, coords_p[1] + 2.5,
                          coords_p[2] - 2.5, coords_p[2] + 2.5)

    # Ritaglia raster locale e trova celle con valore (terraferma)
    r_loc <- tryCatch(terra::crop(raster_cru, ext_loc), error = function(e) NULL)

    if (!is.null(r_loc)) {
      pts_terra <- terra::as.points(r_loc, values = FALSE, na.rm = TRUE)
      if (length(pts_terra) > 0) {
        idx_near <- terra::nearest(p_singolo, pts_terra)$to_id
        coords_near <- terra::crds(pts_terra[idx_near])
        lons_snap[j] <- coords_near[1, "x"]
        lats_snap[j] <- coords_near[1, "y"]
        next
      }
    }
    # Fallback: se attorno c'è solo mare, mantiene le coordinate originali
    lons_snap[j] <- coords_p[1]
    lats_snap[j] <- coords_p[2]
  }

  df_res$lon_snap <- lons_snap
  df_res$lat_snap <- lats_snap

  return(df_res)
}

#' Apply Coordinate Corrections and Generate Final Spatial Vector
#'
#' @description
#' Updates the full dataset of sampling locations by applying user-defined decisions for
#' water-bound sites. Depending on the \code{correction} flag (\code{TRUE} vs \code{FALSE}),
#' the function either shifts points to the nearest land cell (Snap-To-Land) or reverses
#' the sign of the longitude (\code{-Lon}). It then exports an updated audit dataframe and a
#' ready-to-use \code{terra::SpatVector}.
#'
#' @param df_report A \code{data.frame} containing the complete set of stands and baseline metadata
#'   (must contain \code{stand_id}, \code{lon_definitiva}, and \code{lat_definitiva}).
#' @param report_water A \code{data.frame} output by \code{gestisci_punti_in_acqua()} containing water-bound
#'   sites and their calculated snap coordinates (\code{lon_snap}, \code{lat_snap}). Can be \code{NULL}.
#' @param df_correction A \code{data.frame} containing manual correction choices with two columns:
#'   \describe{
#'     \item{\code{stand_id}}{\code{character}. Stand identifier.}
#'     \item{\code{correction}}{\code{logical}. \code{TRUE} to apply Snap-To-Land; \code{FALSE} to apply Longitude Sign Inversion (\code{-Lon}).}
#'   }
#'
#' @return A named \code{list} with two elements:
#'   \describe{
#'     \item{\code{vect}}{A \code{terra::SpatVector} containing all valid corrected points projected in WGS84 (\code{EPSG:4326}).}
#'     \item{\code{df_meta}}{A \code{data.frame} audit report including all stands with added tracking columns:
#'       \describe{
#'         \item{\code{...}}{All original metadata columns from \code{df_report}.}
#'         \item{\code{lon_corretta}}{\code{numeric}. Final corrected longitude.}
#'         \item{\code{lat_corretta}}{\code{numeric}. Final corrected latitude.}
#'         \item{\code{metodo_correzione}}{\code{character}. Method applied: \code{"No Correction"}, \code{"Snap_To_Land"}, or \code{"Inversione_Segno"}.}
#'       }
#'     }
#'   }
#'
#' @importFrom terra vect
#' @export
#'
#' @examples
#' \dontrun{
#' # Define decision data.frame
#' correction_df <- data.frame(
#'   stand_id   = c("esp098", "esp099", "fra059", "swe359"),
#'   correction = c(FALSE, FALSE, TRUE, TRUE) # FALSE = Invert (-Lon), TRUE = Snap
#' )
#'
#' # Apply corrections
#' final_output <- applica_correzioni_coordinate(
#'   df_report     = output_spaziale$df_coor,
#'   report_water  = report_water,
#'   df_correction = correction_df
#' )
#'
#' # Access results
#' spatial_points <- final_output$vect
#' audit_report   <- final_output$df_meta
#' }

applica_correzioni_coordinate <- function(df_report, report_water, df_correction) {

  # 1. Copia di partenza con coordinate definitive
  df_corr <- df_report
  df_corr$lon_corretta <- df_corr$lon_definitiva
  df_corr$lat_corretta <- df_corr$lat_definitiva
  df_corr$water_correction <- "No Correction"

  # 2. Se ci sono stand in acqua, uniamo le info di Snap con le tue decisioni (correction)
  if (!is.null(report_water) && nrow(report_water) > 0) {
    # Merge tra l'audit dell'acqua e il tuo dataframe di decisioni
    df_acqua_decisioni <- merge(report_water, df_correction, by = "stand_id", all.x = TRUE)
    # Se uno stand in acqua non è presente in 'correction', usiamo TRUE (Snap_To_Land) di default
    is_snap <- ifelse(is.na(df_acqua_decisioni$correction), TRUE, df_acqua_decisioni$correction)

    # 3. Calcolo coordinate corrette:
    # FALSE -> Inversione di segno (-Lon)
    # TRUE  -> Snap-To-Land (Avvicinamento alla costa)
    lon_rettificate <- ifelse(is_snap, df_acqua_decisioni$lon_snap, -1 * df_acqua_decisioni$lon_definitiva)
    lat_rettificate <- ifelse(is_snap, df_acqua_decisioni$lat_snap, df_acqua_decisioni$lat_definitiva)
    metodi_applicati <- ifelse(is_snap, "Snap_To_Land", "Inversione_Segno")

    # 4. Aggiornamento nel dataframe totale tramite match
    idx <- match(df_acqua_decisioni$stand_id, df_corr$stand_id)
    valid_idx <- !is.na(idx)
    df_corr$lon_corretta[idx[valid_idx]] <- lon_rettificate[valid_idx]
    df_corr$lat_corretta[idx[valid_idx]] <- lat_rettificate[valid_idx]
    df_corr$water_correction[idx[valid_idx]] <- metodi_applicati[valid_idx]}

  # 5. Filtro per rimuovere eventuali coordinate NA rimaste
  df_valid <- df_corr[!is.na(df_corr$lon_corretta) & !is.na(df_corr$lat_corretta), ]
  # Colonne pulite per la geometria
  df_valid$longitude <- df_valid$lon_corretta
  df_valid$latitude  <- df_valid$lat_corretta

  # 6. Creazione dello SpatVector finale
  punti_geografici_corretti <- terra::vect(
    df_valid,
    geom = c("longitude", "latitude"),
    crs  = "EPSG:4326")
  return(list(
    vect  = punti_geografici_corretti,
    df_meta = df_corr))}
