#' Plot Lag-Response Comparison Curves Across Species Groups for a Given SPEI Value
#'
#' @description
#' Extracts lag-response predictions from a list of fitted DLNM predictions (\code{crosspred} objects)
#' at a specified climate anomaly threshold (\code{valore_spei}). Binds prediction curves and
#' confidence intervals across groups, reverses the x-axis to represent chronological lag steps
#' using custom month labels, and generates a comparative \code{ggplot2} visualization.
#'
#' @param lista_pred A \code{list} of \code{crosspred} objects generated by \code{dlnm::crosspred()}
#' or \code{get_dlnm_pred()}, each corresponding to a specific species group or model.
#' @param valore_spei Numeric vector or single numeric value specifying the SPEI target value(s) to slice
#' from the prediction matrix.
#' @param nomi_gruppi Character vector of group names corresponding to each prediction object in \code{lista_pred}.
#' @param etichette_mesi Character vector of month labels used to annotate the reversed lag x-axis
#' (must contain at least \code{lag_n} labels).
#' @param lag_n Integer. Total number of monthly lags included in the prediction matrix. Default is \code{24}.
#'
#' @return A \code{ggplot} object displaying lag-response curves (fitted values and confidence ribbons)
#' for each group, centered around a reference baseline (y = 1).
#'
#' @import ggplot2
#' @import dplyr
#'
#' @examples
#' \dontrun{
#' library(dplyr)
#' library(ggplot2)
#' library(dlnm)
#'
#' # Mock prediction objects with required matRR matrices
#' mock_pred <- list(
#'   predvar = seq(-2, 2, length.out = 10),
#'   matRRfit = matrix(runif(240, 0.8, 1.2), nrow = 10, ncol = 24),
#'   matRRlow = matrix(runif(240, 0.6, 0.9), nrow = 10, ncol = 24),
#'   matRRhigh = matrix(runif(240, 1.1, 1.4), nrow = 10, ncol = 24)
#' )
#'
#' month_labels <- paste0("M", 1:24)
#'
#' p <- confronto_lag(
#'   lista_pred = list(mock_pred),
#'   valore_spei = 0,
#'   nomi_gruppi = "Fagus",
#'   etichette_mesi = month_labels,
#'   lag_n = 24
#' )
#'
#' print(p)
#' }
#'
#' @export
confronto_lag <- function(lista_pred, valore_spei, nomi_gruppi, lag_n = 24, font = "bold") {
  mesi_sin <- c("sep", "aug", "jul", "jun", "may", "apr", "mar", "feb", "jan")
  mesi_cos <- c("dec", "nov", "oct")
  mesi_eng <- c()
  for (anno in c(0:2))
  {mesi_eng <- c(mesi_eng,str_replace_all(paste(mesi_sin,"-",anno), " ", ""),
                 str_replace_all(paste(mesi_cos,"-",anno+1), " ", ""))}
  estrai_slice <- function(pred_obj, v_var, nome) {
    idx <- which.min(abs(pred_obj$predvar - v_var))
    data.frame(lag = 0:(lag_n-1),
               fit = as.vector(pred_obj$matRRfit[idx, ]),
               low = as.vector(pred_obj$matRRlow[idx, ]),
               high = as.vector(pred_obj$matRRhigh[idx, ]),
               gruppo = nome)}
  df_confronto <- mapply(estrai_slice, lista_pred, valore_spei, nomi_gruppi, SIMPLIFY = FALSE) %>%
    bind_rows()
  ggplot(df_confronto, aes(x = lag, y = fit, color = gruppo, fill = gruppo)) +
    scale_x_reverse(breaks = 0:(lag_n-1), labels = mesi_eng[1:lag_n]) +
    geom_hline(yintercept = 1, linetype = "dashed", color = "black") +
    geom_ribbon(aes(ymin = low, ymax = high), alpha = 0.15, color = NA) +
    geom_line(linewidth = 1) +
    labs(title = paste("SPEI = ",valore_spei," | Tree Growth Response by Genus"),
         x = "Lag (Months)", y = "Regression Coefficient", fill = "Genus", color = "Genus") +
    theme_light() +
    theme(panel.grid.major = element_blank(), # Toglie la griglia principale
          panel.grid.minor = element_blank(),
          axis.text.x = element_text(angle = 35, hjust = 1),
          legend.position = "bottom",
          axis.title.y = element_text(margin = margin(r = 15)),
          axis.title.x = element_text(margin = margin(t = 11)),
          plot.title = element_text(size = 15),
          legend.text = element_text(face = font))}

#' Plot Side-by-Side DLNM Contour Surfaces Across Multiple Models
#'
#' @description
#' Combines multiple DLNM prediction objects (\code{crosspred}) into a unified, faceted 2D contour plot.
#' Visualizes the joint exposure-lag-response surfaces (e.g., SPEI vs. monthly lags) side-by-side using
#' a symmetrical, zero-centered color palette across all specified model comparisons.
#'
#' @param ... Multiple \code{crosspred} objects passed as separate arguments.
#' @param nomi Character vector of labels for each model corresponding to the order of objects passed in \code{...}.
#' If \code{NULL}, names are extracted automatically from input object expressions.
#' @param mesi Character vector of labels used to annotate the discrete monthly lag steps on the y-axis.
#' @param titolo Character string specifying the main title of the generated plot.
#'
#' @return A \code{ggplot} object containing faceted 2D filled contour plots of exposure-lag response surfaces
#' with a shared horizontal color scale at the bottom.
#'
#' @import ggplot2
#' @importFrom grDevices colorRampPalette
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' library(dlnm)
#'
#' # Mock cross-basis prediction objects
#' mock_pred1 <- list(
#'   predvar = seq(-2, 2, length.out = 15),
#'   matfit = matrix(rnorm(15 * 12, mean = 0, sd = 0.5), nrow = 15, ncol = 12)
#' )
#' mock_pred2 <- list(
#'   predvar = seq(-2, 2, length.out = 15),
#'   matfit = matrix(rnorm(15 * 12, mean = 0.2, sd = 0.4), nrow = 15, ncol = 12)
#' )
#'
#' month_names <- paste0("M", 1:12)
#'
#' p <- grafico_unito(
#'   mock_pred1, mock_pred2,
#'   nomi = c("Site A", "Site B"),
#'   mesi = month_names,
#'   titolo = "SPEI Lag-Response Surfaces"
#' )
#'
#' print(p)
#' }
#'
#' @export
grafico_unito <- function(..., nomi, titolo, font = "bold", n_righe = 1) {
  mesi_sin <- c("sep", "aug", "jul", "jun", "may", "apr", "mar", "feb", "jan")
  mesi_cos <- c("dec", "nov", "oct")
  mesi_eng <- c()
  for (anno in c(0:2))
  {mesi_eng <- c(mesi_eng,str_replace_all(paste(mesi_sin,"-",anno), " ", ""),
                 str_replace_all(paste(mesi_cos,"-",anno+1), " ", ""))}
  lista_pred <- list(...)
  nomi_modelli <- nomi
  if (is.null(nomi_modelli)) {
    nomi_modelli <- as.character(substitute(list(...))[-1])}
  prepare_data <- function(pred_obj, model_name) {
    mat <- pred_obj$matfit
    df <- expand.grid(spei = pred_obj$predvar, lag = 0:(ncol(mat) - 1))
    df$fit <- as.vector(mat)
    df$model <- model_name
    return(df)}
  data_all <- do.call(rbind, lapply(seq_along(lista_pred), function(i) {
    prepare_data(lista_pred[[i]], nomi_modelli[i])}))
  data_all$model <- factor(data_all$model, levels = nomi_modelli)
  mia_palette <- colorRampPalette(c("firebrick", "white", "dodgerblue4"))(30)
  max_abs_global <- max(abs(data_all$fit), na.rm = TRUE)

  ggplot(data_all, aes(x = spei, y = lag, z = fit)) +
    stat_contour_filled(aes(fill = after_stat(level_mid)),
                        breaks = seq(-max_abs_global, max_abs_global, length.out = 31)) +
    facet_wrap(~model, nrow = n_righe) +
    scale_fill_gradientn(colors = mia_palette,
                         limits = c(-max_abs_global, max_abs_global), name = "Coefficient",
                         guide = guide_colorbar(
                           direction = "horizontal", # Forza l'orientamento orizzontale
                           barwidth = 14,            # Larghezza della barra (in unità relative)
                           barheight = 1.1,          # Altezza della barra (sottile!)
                           title.position = "top",   # Titolo sopra la barra
                           title.hjust = 0.5,        # Titolo centrato
                           frame.colour = "black",
                           ticks.colour = "black"
                         )) +
    scale_y_continuous(breaks = 0:(length(mesi_eng) - 1),
                       labels = mesi_eng, expand = c(0,0)) +
    theme_minimal() +
    theme(legend.position = "bottom",
          legend.margin = margin(t = 10),
          panel.spacing.x = unit(0, "lines"),
          panel.grid.major = element_line(color = "gray80", linewidth = 0.4),
          panel.grid.minor = element_blank(),
          panel.ontop = FALSE,
          strip.text = element_text(face = font, size = 11, ),
          axis.title.x = element_text(size = 11, margin = margin(t = 11)),
          plot.margin = margin(t = 20, r = 25, b = 20, l = 25, unit = "pt"),
          plot.title = element_text(size = 13, face = "bold", hjust = 0.5, margin = margin(b = 15)),
          axis.title.y = element_text(margin = margin(r = 15)),
          axis.text.y = element_text(size = 10)) +
    labs(title = stringr::str_wrap(titolo, width = 45), x = "SPEI", y = "Lag (Months)")}
